[build]
  base = "/frontend"
  publish = "frontend"
  command = "cd frontend && npm install && npm run build"




[build.environment]
  REACT_APP_GOOGLE_API_TOKEN = "565312274834-licvsp50j3vpa47ckktsi31e3appumns.apps.googleusercontent.com"
  REACT_APP_SANITY_PROJECT_ID = "wl1besem"
  REACT_APP_SANITY_TOKEN = "skfqTM93H0j8Fbnd8XeiTXpMlbWHeQP7FTPtI0J7ICllz5et8ITLg9ukutGq0YeCi5lpxKnBOHSmsEja7Z1at6wvZnngcpTfbgdxZyyAOgX8TmWZsr6oGmnUh7NwAg5fnrhr5jfQ5cCWubM7bSpFlhvO7hvvoO42RskofrI9rIakMxuJ9FY2"
